#!/bin/sh
set -e
lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free-firmware" \
  --binary-images iso-hybrid \
  --bootloaders "syslinux,grub-efi" \
  --debian-installer none \
  --firmware-chroot true \
  --security true --updates true \
  --iso-application "EPIC OS" \
  --iso-publisher "EPIC OS Project" \
  --iso-volume "EPIC_OS" \
  --image-name "epic-os-x64" \
  --bootappend-live "boot=live components quiet splash username=epic hostname=epicos locales=en_US.UTF-8 keyboard-layouts=us" \
  "${@}"
